### PR TITLE
Source should be a valid url

### PR DESCRIPTION
**Pull request by razzeee**

### CODE REVIEW

**Comment by cdwertmann** [comment]
URLs starting with git:// are still valid URLs

**Comment by razzeee** [comment]
Correct, but browsers won't know what to do when you hit this URL. Advanced users will know, but that's not exactly what we're after. 
Also see http://kodi.wiki/view/Addon.xml#.3Csource.3E

**Comment by cdwertmann** [comment]
I'd say that people who want to look at the source code of a plugin generally know what to do with a git protocol URL. The Kodi documentation that you pointed to does not explicitly state that this must be a HTTP URL.

**Comment by razzeee** [comment]
I'm just saying that your not using it as everybody else is.
So http://addons.kodi.tv/show/plugin.audio.rainymood.com for example links to a site which will prompt tortoiseGit for me. Which is fine, but I might want to look at documentation first. And not everybody will have something installed that handles `git://`

**Comment by cdwertmann** [comment]
OK. I wasn't aware that they use it as a link on their website.

**Comment by MartijnKaijser** [comment]
could you send an update to kodi repo for this?

Btw this addons is my most used addon i have installed :)

**Pull request merged**
